version: "3"
services:
  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "8006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: buk
      MYSQL_USER: buk
      MYSQL_PASSWORD: buk
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"

  web:
    build: docker-php
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
    depends_on:
      - db
